inputSet:
  name: Build_rflemig_ApresentacaoPrometheus_1705082000174-pr-trigger-input-set
  identifier: Build_rflemig_ApresentacaoPrometheus_1705082000174prtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_rflemig_ApresentacaoPrometheus_1705082000174
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
